apiVersion: v1
kind: ReplicationController
metadata:
  name: openvpn
spec:
  replicas: 1
  selector:
    app: openvpn
  template:
    metadata:
      labels:
        app: openvpn
    spec:
      containers:
        - name: openvpn
          image: redspreadapps/kube-openvpn
          #image: gcr.io/redspreadprod/openvpn
          command: ["start.sh"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          imagePullPolicy: Always
          ports:
            - containerPort: 1194
              protocol: TCP
          env:
            - name: OVPN_HOST
              value: cluster.joopal
      restartPolicy: Always
      dnsPolicy: ClusterFirst
